language: java

before_script:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git beluga https://github.com/HaxeBeluga/Beluga
  - haxelib install session

script:
  - haxe BelugaDemo.hxml

notifications:
  slack: beluga:TnSEYGr5VTjnqJkbFKMhJorQ
